name: CI

on:
  push:

permissions:
  contents: read

jobs:
  build-app:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: ./aroundtech
        run: npm install
      - name: Build
        working-directory: ./aroundtech
        run: npm run build
